environment:
  PYPI_PASSWD:
    secure: w16EmxgfwQdS1FLB/PCWQA==

  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

branches:
  only:
    - master
    - release

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%WITH_COMPILER% %PYTHON%/python -V"
  - cmd: nuget install redis-64 -excludeversion
  - cmd: redis-64\tools\redis-server.exe --service-install
  - cmd: redis-64\tools\redis-server.exe --service-start

build: off

test_script:
  - "%WITH_COMPILER% %PYTHON%/python setup.py test -q --io proactor --sequential"
  - "%WITH_COMPILER% %PYTHON%/python setup.py sdist"

after_test:
  - ps: >-
      if($env:appveyor_repo_branch -eq 'release') {
          Invoke-Expression "$env:PYTHON\\python.exe -m twine upload dist/* --username lsbardel --password $env:PYPI_PASSWD"
      }
